### ISSUE TITLE
Switch to libjpeg-turbo?

### ISSUE THREAD

**Issue by cmb69** [winlibs/libjpeg#4]
It might be reasonable to consider to replace libjpeg with [libjpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo). The latter is supposed to be [faster](https://libjpeg-turbo.org/About/Performance), several Linux distros use it (e.g. [Debian](https://packages.debian.org/stretch/libjpeg-dev) and [Fedora](https://fedoraproject.org/wiki/Features/libjpeg-turbo)), and its development appears to be more transparent and open (to my knowledge, there are few if any ways to contribute back to IJG's libjpeg). There is also quite some criticism regarding how libjepg has been evolved in the last years (e.g. expressed in a mail by [Thomas Lane](https://lists.fedoraproject.org/pipermail/devel/2013-January/176400.html), the former organizator of IJG).

GD (bundled as well as external) work fine with libjpeg-turbo on Linux, so I expect few if any issues on Windows.

**Comment by weltling** [comment]
A couple of years ago libjpeg-turbo has been evaluated as well, but the doc told it would only support some quite old interface corresponding to the version from ijg.org. I'm not very deep into libgd, so it sounded actually like some features could be missing. So the idea was abandoned at that point. The speedup sounded promising, of course.

This sure could be reconsidered. Do you plan to move ext/gd to libjpeg-turbo? Perhaps checking that it has no regressions on Linux would be the first step. Building for Windows seems to be no issue according to https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/BUILDING.md#windows.

Thanks.

**Comment by cmb69** [comment]
> Do you plan to move ext/gd to libjpeg-turbo?

ext/gd already works fine with libjpeg-turbo (actually I'm usually building against libjpeg-turbo instead of libjpeg, and I haven't yet noticed any issues). And to my knowledge, libgd doesn't use any of the post libjpeg 6 features (at least some would be incompatible with a lot of other image readers/processors; which is one of the reasons why libjpeg-turbo doesn't introduce these features). I'll verify this ASAP, though.

**Comment by cmb69** [comment]
Done with 81e8fc49805bffc88682fad567b63cbe4aceaae2.

**Comment by Neustradamus** [comment]
@cmb69: Can you rename this repository?

After rename, no lost, GitHub adds redirections.

**Comment by cmb69** [comment]
I see no point in renaming. After all, we're doing libjpeg compatible builds (not using any of the incompatible -turbo advancements), and maybe we're switching to another library in the future (no plans, but who knows).
