### ISSUE TITLE
A out of bound read bug in libjpeg-9b

### ISSUE THREAD

**Issue by zzyyrr** [winlibs/libjpeg#5]
Hi,

I'm using fuzzing to detect vulnerabilitises in some real-word applications. I found a out of bound read in libjpeg-9b.
In the cjpeg.c file,code:num_scanlines=(*src_mgr->get_pixel_rows)(&cinfo,src_mgr), the function: read_pbm_integer(cinfo, infile) in rdmmp.c. Its return value may beyond the boundary of array: reacale.

This is my command:
cat ./id:000004,sig:11,src:000606,op:havoc,rep:2 | valgrind ./cjpeg_01 

This is the debug information:
==2221842== Memcheck, a memory error detector
==2221842== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2221842== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==2221842== Command: ./cjpeg_01
==2221842== 
==2221842== Invalid read of size 1
==2221842==    at 0x402787: get_text_rgb_row (rdppm.c:171)
==2221842==    by 0x400D9D: main (cjpeg.c:642)
==2221842==  Address 0x59fa7195 is not stack'd, malloc'd or (recently) free'd
==2221842== 
==2221842== 
==2221842== Process terminating with default action of signal 11 (SIGSEGV)
==2221842==  Access not within mapped region at address 0x59FA7195
==2221842==    at 0x402787: get_text_rgb_row (rdppm.c:171)
==2221842==    by 0x400D9D: main (cjpeg.c:642)
==2221842==  If you believe this happened as a result of a stack
==2221842==  overflow in your program's main thread (unlikely but
==2221842==  possible), you can try to increase the size of the
==2221842==  main thread stack using the --main-stacksize= flag.
==2221842==  The main thread stack size used in this run was 8388608.
==2221842== 
==2221842== HEAP SUMMARY:
==2221842==     in use at exit: 1,942,168 bytes in 12 blocks
==2221842==   total heap usage: 13 allocs, 1 frees, 1,946,264 bytes allocated
==2221842== 
==2221842== LEAK SUMMARY:
==2221842==    definitely lost: 0 bytes in 0 blocks
==2221842==    indirectly lost: 0 bytes in 0 blocks
==2221842==      possibly lost: 0 bytes in 0 blocks
==2221842==    still reachable: 1,942,168 bytes in 12 blocks
==2221842==         suppressed: 0 bytes in 0 blocks
==2221842== Rerun with --leak-check=full to see details of leaked memory
==2221842== 
==2221842== For lists of detected and suppressed errors, rerun with: -s
==2221842== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault

[cjpeg-crash.zip](https://github.com/winlibs/libjpeg/files/5061424/cjpeg-crash.zip)

**Comment by cmb69** [comment]
While this repo may be affected, we do not ship binary builds of cjeg.exe, and just switched to libjpeg-turbo, so this ticket is considered irrelevant and obsolete. Please report such issues to the upstream repositories, if they are still relevant. We do our best to update from there as needed.
